/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import datamahasiswa.Student;
import java.util.ArrayList;
import controller.StudentController;
import datamahasiswa.Course;
import datamahasiswa.Course;
import datamahasiswa.KRS;
import datamahasiswa.KRS;
import datamahasiswa.Lecturer;
import datamahasiswa.Lecturer;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yulia
 */
public class InputNilai extends javax.swing.JFrame {
    ArrayList<Student> listMahasiswa = new ArrayList<>();
    ArrayList<Course> listMK = new ArrayList<>();
    ArrayList<Lecturer> listLecture=new ArrayList<>();
    final String[] semester={"1","2","3"};
    final DefaultComboBoxModel comboModelSM= new DefaultComboBoxModel(semester);
    DefaultComboBoxModel<Student> comboModelMhs = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<Course> comboModelCourse = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<Lecturer> comboModelLecturer = new DefaultComboBoxModel<>();
    Student selecttedStudent;
    Course selecttedCourse;
    KRS krs;
    Lecturer selectedLecture;
    StudentController controller = new StudentController();

    public InputNilai() {
        initComponents();
        ArrayList<Student> listMahasiswa = (ArrayList<Student>) controller.getStudent();
//        listMahasiswa.add(new Student("199000299","Andi","001", "Ilmu Komputer"));
//        listMahasiswa.add(new Student("19920992","AGus Jaya","002", "Ilmu Komputer"));
//        listMahasiswa.add(new Student("19912992","Deni Mudia","003", "Ilmu Komputer"));
        listMK.add(new Course("010", "OOP", 3, 2));
        listMK.add(new Course("011", "English", 3, 2));
        listMK.add(new Course("012", "Web", 3, 2));
        listMK.add(new Course("013", "Mobile", 3, 2));
        listLecture.add(new Lecturer("ID01","Agus","092999","Web"));
        listLecture.add(new Lecturer("ID02","Sanjaya Putra","0888899","Mobile"));
        for(Lecturer item:listLecture){
            comboModelLecturer.addElement(item);
        }
        for (Student student : listMahasiswa) {
            comboModelMhs.addElement(student);
        }
        for (Course course : listMK) {
            comboModelCourse.addElement(course);
        }
        
        jComboBoxMhs.setSelectedIndex(0);
        jComboBoxCourse.setSelectedIndex(0);
        jComboBoxDosen.setSelectedIndex(0);

        selecttedStudent = (Student) jComboBoxMhs.getSelectedItem();
        selecttedCourse = (Course) jComboBoxCourse.getSelectedItem();
        selectedLecture = (Lecturer) jComboBoxDosen.getSelectedItem();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNilai = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxMhs = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabelNIM = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNilaiSikap = new javax.swing.JTextField();
        jTextFieldNilaiUTS = new javax.swing.JTextField();
        jTextFieldNilaiUAS = new javax.swing.JTextField();
        jButtonAdd = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabelKodeSKS = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelHuruf = new javax.swing.JLabel();
        jComboBoxSM = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxCourse = new javax.swing.JComboBox<>();
        jComboBoxDosen = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableNilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIM", "NAMA", "Matakuliah", "SKS", "Nilai", "Dosen"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableNilai);

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel5.setText("Form Input Nilai");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Identitas Mahasiswa"));
        jPanel1.setToolTipText("");
        jPanel1.setName(""); // NOI18N

        jLabel1.setText("Nama");

        jComboBoxMhs.setModel(comboModelMhs);
        jComboBoxMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMhsActionPerformed(evt);
            }
        });

        jLabel4.setText("NiM & Prodi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxMhs, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxMhs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabelNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Identitas Matakuliah"));

        jLabel2.setText("Matakuliah");

        jLabel3.setText("Nilai");

        jTextFieldNilaiSikap.setText("0");
        jTextFieldNilaiSikap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNilaiSikapActionPerformed(evt);
            }
        });

        jTextFieldNilaiUTS.setText("0");
        jTextFieldNilaiUTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNilaiUTSActionPerformed(evt);
            }
        });

        jTextFieldNilaiUAS.setText("0");
        jTextFieldNilaiUAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNilaiUASActionPerformed(evt);
            }
        });

        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jLabel7.setText("Kode dan SKS");

        jLabelKodeSKS.setText("Kode SKS");

        jLabel8.setText("Nilai Huruf");

        jLabelHuruf.setText("Nilai Huruf");

        jComboBoxSM.setModel(comboModelSM);
        jComboBoxSM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSMActionPerformed(evt);
            }
        });

        jLabel6.setText("Semester");

        jComboBoxCourse.setModel(comboModelCourse);
        jComboBoxCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCourseActionPerformed(evt);
            }
        });

        jComboBoxDosen.setModel(comboModelLecturer);
        jComboBoxDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDosenActionPerformed(evt);
            }
        });

        jLabel9.setText("Pengampu");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(25, 25, 25)
                            .addComponent(jLabelHuruf)
                            .addGap(80, 80, 80)
                            .addComponent(jButtonAdd)
                            .addGap(33, 33, 33))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(jComboBoxCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldNilaiSikap, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldNilaiUTS, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldNilaiUAS, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(41, 41, 41)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxSM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelKodeSKS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabelKodeSKS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldNilaiSikap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldNilaiUTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldNilaiUAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxSM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabelHuruf)
                    .addComponent(jButtonAdd))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMhsActionPerformed
        // TODO add your handling code here:
        this.selecttedStudent= (Student) jComboBoxMhs.getSelectedItem();
        if(selecttedStudent != null){
            jLabelNIM.setText(selecttedStudent.getNim()+ " | Prodi: " + selecttedStudent.getStudyProgram());
        }
    }//GEN-LAST:event_jComboBoxMhsActionPerformed

    private void jComboBoxSMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSMActionPerformed
        // TODO add your handling code here:
        setKRS();
        jLabelHuruf.setText(this.krs.getGrade());
    }//GEN-LAST:event_jComboBoxSMActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here
    // Membuat objek KRS terlebih dahulu
    setKRS();

    // Cek apakah mahasiswa sudah dipilih
    if (selecttedStudent == null) {
        JOptionPane.showMessageDialog(this, "Pilih mahasiswa terlebih dahulu!");
        return;
    }

    // Cek apakah KRS berhasil dibuat
    if (krs == null) {
        JOptionPane.showMessageDialog(this, "KRS gagal dibuat!");
        return;
    }

    // Simpan KRS ke mahasiswa
    selecttedStudent.addKRS(krs);

    // Tambahkan ke tabel
    DefaultTableModel model = (DefaultTableModel) jTableNilai.getModel();

    model.addRow(new Object[]{
        selecttedStudent.getNim(),
        selecttedStudent.getName(),
        krs.getCourse().getNamaMK(),
        krs.getCourse().getSks(),
        krs.getGrade(),
        krs.getLecture().toString()
    });
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jTextFieldNilaiUASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNilaiUASActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFieldNilaiUASActionPerformed

    private void jTextFieldNilaiUTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNilaiUTSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNilaiUTSActionPerformed

    private void jTextFieldNilaiSikapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNilaiSikapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNilaiSikapActionPerformed

    private void jComboBoxCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCourseActionPerformed
        // TODO add your handling code here:
       this.selecttedCourse = (Course) jComboBoxCourse.getSelectedItem();
    if (selecttedCourse != null) {
        jLabelKodeSKS.setText(selecttedCourse.getKode() + " | SKS: " + selecttedCourse.getSks());
    }

        
    }//GEN-LAST:event_jComboBoxCourseActionPerformed

    private void jComboBoxDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDosenActionPerformed
        // TODO add your handling code here:
        this.selectedLecture=(Lecturer) jComboBoxDosen.getSelectedItem();
    }//GEN-LAST:event_jComboBoxDosenActionPerformed
   private void setKRS() {

    if (selecttedCourse == null) {
        JOptionPane.showMessageDialog(this, "Pilih mata kuliah terlebih dahulu!");
        return;
    }

    if (selectedLecture == null) {
        JOptionPane.showMessageDialog(this, "Pilih dosen terlebih dahulu!");
        return;
    }

    int uas = Integer.parseInt(jTextFieldNilaiUAS.getText());
    int uts = Integer.parseInt(jTextFieldNilaiUTS.getText());
    int sikap = Integer.parseInt(jTextFieldNilaiSikap.getText());

    double rataRata = (uas + uts + sikap) / 3.0;

    krs = new KRS(selecttedCourse, rataRata);
    krs.setLecture(selectedLecture);
    krs.setSemester(jComboBoxSM.getSelectedIndex());
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputNilai().setVisible(true);
            }
        });
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JComboBox<Course> jComboBoxCourse;
    private javax.swing.JComboBox<Lecturer> jComboBoxDosen;
    private javax.swing.JComboBox<Student> jComboBoxMhs;
    private javax.swing.JComboBox<String> jComboBoxSM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelHuruf;
    private javax.swing.JLabel jLabelKodeSKS;
    private javax.swing.JLabel jLabelNIM;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableNilai;
    private javax.swing.JTextField jTextFieldNilaiSikap;
    private javax.swing.JTextField jTextFieldNilaiUAS;
    private javax.swing.JTextField jTextFieldNilaiUTS;
    // End of variables declaration//GEN-END:variables
    
//    DefaultComboBoxModel<Student> comboModelMhs = new DefaultComboBoxModel<>();
//    for (Student student : listMahasiswa) {
//    comboModelMhs.addElement(student);
//}
}